#!/bin/sh

#set -x 

TOKEN=`lpass show -j 5571568052 | jq -r '.[].note' | head -1`

#echo ">$TOKEN<"

export URL=https://gitlab.com/api/v4/

curl --header "PRIVATE-TOKEN: $TOKEN" -s https://gitlab.com/api/v4/users/wkoszek/projects| jq -r ".[].name"
