#!/usr/bin/env ruby

require 'Gitlab'
require_relative 'gitlab.rb'

gitlab_init

if ARGV.length < 1
  puts "Usage:"
  puts "\tgitlab_repo_rm <name>"
  exit 2
end

repo_name = ARGV[0]

if not repo_name =~ /^wkoszek/
  repo_name = "wkoszek/" + repo_name
end

puts "# repo: #{repo_name}"

Gitlab.delete_project(repo_name)
