#!/usr/bin/env ruby

require 'Gitlab'
require 'fileutils'
require_relative 'gitlab.rb'

gitlab_init


if ARGV.length < 1
  puts "Usage:"
  puts "\tgitlab_repo_rm <name>"
  exit 2
end
repo_name = ARGV[0]
#if not repo_name =~ /^wkoszek/
#  repo_name = "wkoszek/" + repo_name
#end

options = {}

repo_desc = "desc"

options = {}
options[:description] = repo_desc
options[:default_branch] = "master"
options[:wiki_enabled] = 0
options[:wall_enabled] = 0
options[:issues_enabled] = 0
options[:snippets_enabled] = 0
options[:merge_requests_enabled] = 0
options[:public] = 0

puts "# options"
puts options

Gitlab.create_project(repo_name, options)
FileUtils.mkdir(repo_name)
File.write("#{repo_name}/README.md", "# #{repo_desc}")
Dir.chdir("#{repo_name}")

`git init`
`git remote add origin git@gitlab.com:wkoszek/#{repo_name}.git`
`git add README.md`
`#{ENV['HOME']}/r/tools/git_author_start`
`git commit -m "#{repo_desc}"`
`git push -u origin master`
